title: Run away bread, before the teeth bites you.
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Epic tales about my life. Have a laugh, doubt about the incredible things that have happened to me and use some of the advices in any way they fit you.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  glengleniri # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minina
